name: test_hotel
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.9
  go_router: ^13.0.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SFProDisplay/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/SFProDisplay/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: assets/fonts/SFProDisplay/SF-Pro-Display-Semibold.otf
          weight: 600
